#ifndef __HTTP__
#define __HTTP__

#define SERVER_NAME 		"swebs"
#define SERVER_VERSION	"1.3"
#define MIME_HTML			 	"text/html"

/* HTTP CODE */

#define HTTP_CODE_200  200
#define HTTP_CODE_400  400
#define HTTP_CODE_403  403
#define HTTP_CODE_404  404
#define HTTP_CODE_500  500

#define RESPONSE_200 "HTTP/1.1 200 OK\r\n"
#define RESPONSE_400 "HTTP/1.1 400 Bad Request\r\n"
#define RESPONSE_403 "HTTP/1.1 403 Forbidden\r\n"
#define RESPONSE_404 "HTTP/1.1 404 Not Found\r\n"
#define RESPONSE_500 "HTTP/1.1 500 Internal Server Error\r\n"

#define RESPONSE_200_SIZE 17
#define RESPONSE_400_SIZE 26
#define RESPONSE_403_SIZE 24
#define RESPONSE_404_SIZE 24
#define RESPONSE_500_SIZE 36

/* END HTTP CODE */

/* HEADERS */

#define HEADER_SERVER 				"Server: "SERVER_NAME"/"SERVER_VERSION" (Unix)\r\n"
#define HEADER_KEEP_ALIVE			"Keep-Alive: timeout=5\r\n"
#define HEADER_CONNECTION			"Connection: Keep-Alive\r\n"
#define HEADER_CONTENTTYPE		"Content-Type: "
#define HEADER_CONTENTLENGHT	"Content-Length: "
#define HEADER_USERAGENT      "User-Agent: "

#define HEADER_SERVER_SIZE 				26
#define HEADER_KEEP_ALIVE_SIZE 		23
#define HEADER_CONNECTION_SIZE 		24
#define HEADER_CONTENTTYPE_SIZE 	14
#define HEADER_CONTENTLENGHT_SIZE 16
#define HEADER_USERAGENT_SIZE     12

#define TOTAL_HEADER_SIZE HEADER_SERVER_SIZE+HEADER_KEEP_ALIVE_SIZE+HEADER_CONNECTION_SIZE+HEADER_CONTENTTYPE_SIZE+2+HEADER_CONTENTLENGHT_SIZE+2+2

#define HEADER_200_SIZE RESPONSE_200_SIZE+TOTAL_HEADER_SIZE
#define HEADER_400_SIZE RESPONSE_400_SIZE+TOTAL_HEADER_SIZE
#define HEADER_403_SIZE RESPONSE_403_SIZE+TOTAL_HEADER_SIZE
#define HEADER_404_SIZE RESPONSE_404_SIZE+TOTAL_HEADER_SIZE
#define HEADER_500_SIZE RESPONSE_500_SIZE+TOTAL_HEADER_SIZE

/* END HEADERS */

#endif
